### ISSUE TITLE
What is the status on installing IEC Certification Kit without --source?

### ISSUE THREAD

**Issue by aander80** [mathworks-ref-arch/matlab-dockerfile#117]
Hello!

Currently, installing IEC Certification Kit is a hassle since you need to download a full installation image before you can install a small tool. What is the status on adding native support for IEC Certification Kit in mpm without --source and a separate image?

**Comment by ekapoun1** [comment]
Also interested in this. It does feel like an afterthought to have to install the toolkit separately compared to other toolkits.

**Comment by sbnicholas** [comment]
IEC Certification Kit has authentication requirements MPM cannot currently meet, which is why a separate download is needed to install it. We're exploring other ways we could meet these requirements without relying on the full installation image, but I don't have a time estimate for when such an enhancement will be available. In the meantime, I will pass this request along to the MPM development team.
