### ISSUE TITLE
Does license.dat issued from educational mathwork account different from individual 

### ISSUE THREAD

**Issue by xinqin23** [mathworks-ref-arch/matlab-dockerfile#29]
Hi! I am following the step [here](https://github.com/mathworks-ref-arch/matlab-dockerfile#use-a-license-file-to-build-image)

And may I consult will the license.dat issued(installed through network manager) using the educational account, different from the ones issued through individual license?

I copied the Host ID e.g.  3C6AA751**** into the SERVER line. 

Then when trying to run Matlab in docker it will get:
`Licensing error: -9,57.`

For some reason I have to use this user provided container, but having trouble to link matlab into it ...

Sorry for the disturbance
Thank you for reading!!
Best,
Xin

**Comment by fallimathworks** [comment]
Are you attempting to use a Individual license or a Concurrent license? The reference architecture is for a network license setup. The error you are receiving generally happens when you attempt to use a Individual or Designated Computer license. For a network setup make a network.lic and place it in the directory that you have the docker file. Then use line 176 of the following: https://github.com/mathworks-ref-arch/matlab-dockerfile/blob/master/Dockerfile. If you continue to have issues or want to install a Individual license using docker please call Installation and Licensing Support. We can be reached at +1-508-647-7000. Dial option 3, then 1 at the menu.

**Comment by xinqin23** [comment]
Hi!!! I am using an Educational license! From the math work website, it indicates the license is "individual".

Let me dumbly double-check: so for the individual license, there might need some other steps to install it into the docker right... 

Let me reach out to the phone number!

Thank you so much!!

Best Regards, 
Xin
