### ISSUE TITLE
DisplayError: No Display available - R2020b

### ISSUE THREAD

**Issue by Castronova** [mathworks-ref-arch/matlab-dockerfile#31]
I'm attempting to build r2020b using the instructions in this repository and I'm encountering the following error when running `install`:

```
./install --inputFile /matlab_installer_input.txt -licensePath /tmp/network.lic 
```

```
terminate called after throwing an instance of '(anonymous namespace)::DisplayError'
  what():  No display available.
Aborted (core dumped)
```

**Comment by josmartin** [comment]
@Castronova I'm a bit confused? Is the result above something you got as part of running 

```
docker build -t matlab:r2020a --build-arg LICENSE_SERVER=27000@MyServerName .
```

Could you paste the full log from your docker build output so that we can see how the above fits with the rest of the docker build phase? Particularly in our Dockerfile I've expressly added the `-mode silent` flag to run the silent installer as there is no display available in the docker build environment.

**Comment by Castronova** [comment]
After more digging I was able to find the following in the installation logs:

> (Mar 10, 2021 21:20:19) Not a valid key. For more information on how to generate a valid key see this MATLAB Answer.
> (Mar 10, 2021 21:20:19) Exiting with status -2
> (Mar 10, 2021 21:20:19) End - Unsuccessful

Closing because the doesn't appear to be an issue with the installer.
