### ISSUE TITLE
License File Error: Unable to read license file

### ISSUE THREAD

**Issue by blankered** [mathworks-ref-arch/matlab-dockerfile#32]
I am attempting to load a dedicated license into the docker container. I put the license.lic in the root directory and uncommented line 181 in the docker

ADD license.lic /usr/local/MATLAB/$MATLAB_RELEASE/licenses/license.lic

and uncommented line 87 in matlab_installer_inputs.txt

licensePath = /usr/local/MATLAB/$MATLAB_RELEASE/licenses/license.lic

![image](https://user-images.githubusercontent.com/11299739/112146683-3edc5a00-8bb2-11eb-877e-32e33bc28056.png)

EDIT:

It appears the Matlab looks for the license file before it is moved in the Dockerfile. I dumped the license file into the matlab-install directory and search for it there as the directory is migrated to the docker image in the dockerfile. This seems to resolve the issue.

**Comment by josmartin** [comment]
Do note: the `matlab_installer_inputs.txt` does not expand environment variables which is why it was attempting to look for your license in the literal file `/usr/local/MATLAB/$MATLAB_RELEASE/licenses/license.lic` (notice the unexpanded `$MATLAB_RELEASE` text. I suspect that if you were to replace that correctly - or put the file in a well-known location (which is what your EDIT does) it will all work.
