### ISSUE TITLE
Your username does not match the username in the license file

### ISSUE THREAD

**Issue by rogelioamancisidor** [mathworks-ref-arch/matlab-dockerfile#33]
I add the license.lic file, that I got at step 3, to the Dockerfile. However when I build the image I get this error:
 
    MATLAB is selecting SOFTWARE OPENGL rendering.
    License checkout failed.
    License Manager Error -9
    Your username does not match the username in the license file. 
    To run on this computer, you must run the Activation client to reactivate your license.

    Troubleshoot this issue by visiting: 
     https://www.mathworks.com/support/lme/R2021a/9

    Diagnostic Information:
    Feature: MATLAB 
    License path: /root/.matlab/R2021a_licenses:/usr/local/MATLAB/licenses/license.dat:/usr/local/MATLAB/licenses/lice
    nse.lic 
    Licensing error: -9,57.

it seems like the host id that i specified is correct but not the computer login name. What is the name that I should use to generate the license file and installation key?

**Comment by josmartin** [comment]
@rogelioamancisidor currently the ```matlab-dockerfile``` generated image only supports using a FlexLM license server as the way to provide it with a MATLAB license. Thus the file you are supplying (```license.dat```) should point to a Flex LM server. As an alternative you can simply specify the ```port@hostname``` for this server in the ```--build-arg LICENSE_SERVER=27000@MyServerName``` when building the image. I believe the error you are getting results from attempting to use an individual license, rather than a FlexLM served license.

**Comment by rogelioamancisidor** [comment]
can I find my port@hostname in some license file, or in my profile at mathworks, or do I need to contact my admin?

**Comment by josmartin** [comment]
@rogelioamancisidor You will need to contact your license admin (who runs this server). This is not information that MathWorks hold.

**Comment by rogelioamancisidor** [comment]
thanks @josmartin. Just to make sure I understand how the image is created and the license validated, providing the LICENSE_SERVER=27000@MyServerName parameter, the license is obtained from a server in a secure way right? So I can push that image to my hubdocker?

**Comment by josmartin** [comment]
@rogelioamancisidor Yes - all that ```--build-arg LICENSE_SERVER=27000@MyServerName``` does is bind into the docker image the correct data so that MATLAB (when it is started) will contact that license server (which is assumed to be on your company / university network) to acquire a license. BTW - just so you are aware, if the only product you are building into the container is MATLAB you might be interested in this [pre-built docker image on dockerhub](https://hub.docker.com/r/mathworks/matlab).

**Comment by omikader** [comment]
Hi @josmartin, is there any way to add supplementary toolboxes onto the pre-built docker image that you are referring to? Or is the only option to use the instructions in this repository? Thanks.

**Comment by josmartin** [comment]
@omikader You can find instructions for adding toolboxes to our pre-built containers [here](https://www.mathworks.com/help/cloudcenter/ug/matlab-deep-learning-container-on-dgx.html#mw_4af50c8a-22f1-4c6e-a299-1c834aafeb5e_sep_mw_ac5f8e10-286c-4593-9564-deb2f6279ae0).

**Comment by omikader** [comment]
@josmartin If I understand correctly, it looks like a GUI is required for this section in the docs. Is that correct? I was hoping to find a way where I could possibly alter a file similar to `matlab_installer_input.txt` and rebuild the container with the updated toolbox (e.g. Parallel Computing)

**Comment by josmartin** [comment]
@omikader If you want to follow a ```docker build``` type scripted process then you should use something like the instructions in this repo and simply augment the MATLAB install in our dockerhub container with additional toolboxes. Since it already contains the base MATLAB product you don't need to include that - you can start ```FROM mathworks/matlab``` and carry out the additional installation by following all the instructions in this repo (having downloaded for offline installation for example Parallel Computing Toolbox).
