### ISSUE TITLE
Removing licensing information after procedure completes

### ISSUE THREAD

**Issue by jasonmeverett** [mathworks-ref-arch/matlab-dockerfile#36]
Hello,

I'd like the ability to run the step of this procedure that installs extra toolboxes, but then remove all licensing information from the image before committing the updated image to a repository. 

We are currently working with a CI/CD configuration that does not support remote agents, and therefore our Docker image needs to be uploaded to Docker Hub. Because of this, we do not want to store any private information such as license files in the image itself. We would like the user of the image to have to supply their own license file through an environment variable, where the license file applied contains privileges to all of the installed toolboxes.

I don't currently see a feature in this workflow that allows us to install components with a license, but yet also remove all cached licensing information before committing a final Docker image. Is this capability possible?

Thanks,
Jason

**Comment by jasonmeverett** [comment]
Update: I've tried several different ways to get rid of licensing information, none of them seem to work.

I've tried removing the `MLM_LICENSE_FILE` from the relative environments:
```
unset MLM_LICENSE_FILE
sudo su
unset MLM_LICENSE_FILE
```

I've tried also removing the `MLM_LICENSE_FILE` lines in `.bashrc` (for the `matlab` profile). However, when all of those things are deleted and if I try to run a `docker commit` to commit the "unlicensed" version of the image, and then rerun the image without licensing information, for some reason, the license information still persists within that container!

**Comment by josmartin** [comment]
@jasonmeverett 

The `Dockerfile` as written in this repo should ONLY put licensing info into the `MLM_LICENSE_FILE` environment variable (or possibly a `network.lic` file if you included that in the `matlab-install` folder when you ran the silent installer). This first container would be the result of a `docker build` command and should NOT contain any other licensing info. Also, you should be able to incorporate any products you need in this single build. 

I'm a little confused by what you say above, since the use of `docker commit` suggests that you may have built a container, then run it, then somehow added more products to the running container (probably needing a license), and finally committed that new container. That workflow would seem to suggest that at some point you needed to add a license and it is that license that you see in the committed container.

When you say that the container you commit has a license - do you know where that license is (in the file-system)? Most likely places are `MATLABROOT`, `MATLABROOT/licenses` or `cwd`. 

I'd be happy to take this off-line and chat directly to work out more if you need - do let us know.

**Comment by jasonmeverett** [comment]
@josmartin 

The latter actually is what I'm doing. I really should have opened up a different ticket elsewhere, and I realize that now. Apologies. I am opening my original docker image, then using `commit` (after installing items that needed a license) to create a new image. I think that during that commit process, the licensing information I add gets "boiled in" to the image, and then allows me to start the image without passing in an environment file parameter (which, again, is undesired).

On line 7 of my copied-over `matlab_installer_input.txt` file, I've set:
```
destinationFolder=/opt/matlab/R2020b
fileInstallationKey=<our network license key>
product.MATLAB (uncommented)
agreeToLicense=yes
```

I've also added a few other things to the `Dockerfile` to set paths and versions. I'm now getting this error:

```
(Sep 29, 2021 20:04:34) Reading from /matlab-install/archives
(Sep 29, 2021 20:04:34) Starting local product/component search in download directory
(Sep 29, 2021 20:04:34) Searching for archives...
(Sep 29, 2021 20:04:34) Reading /matlab-install/archives
(Sep 29, 2021 20:04:34) 24 files found in /matlab-install/archives
(Sep 29, 2021 20:04:34) Archive search complete.  24 total files found.
(Sep 29, 2021 20:04:34) Completed local product/component search
(Sep 29, 2021 20:04:34) Finished reading from/matlab-install/archives
(Sep 29, 2021 20:04:34) Missing Installation Files: Unable to locate the required files.

To use a File Installation Key, you must run the installer from a directory that contains the installation files.

For information on how to get the files, see this MATLAB Answer.
        at com.mathworks.install_core_common.MATLABInstallerExceptionUtil.getApplicationException(MATLABInstallerExceptionUtil.java:16)
        at com.mathworks.matlab_installer.services.MatlabInstallerServices.checkArchives(Unknown Source)
        at com.mathworks.installservicehandler.context.ExceptionInterceptor.invoke(ExceptionInterceptor.java:21)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.mathworks.installservicehandler.JsonPassThroughResponseWrapper.getData(JsonPassThroughResponseWrapper.java:24)
        at com.mathworks.installservicehandler.JsonPassThroughResponseWrapper.getData(JsonPassThroughResponseWrapper.java:10)
        at com.mathworks.installservicehandler.InstallServiceHandlerClient.executeService(InstallServiceHandlerClient.java:18)
        at com.mathworks.matlab_installer.MatlabInstallerClient$3.executeService(Unknown Source)
        at com.mathworks.installjscommon.InstallerClientUtility.executeGetNextStateInSequence(Unknown Source)
        at com.mathworks.matlab_installer.MatlabInstallerClient.clientMain(Unknown Source)
Caused by: java.lang.Exception: Installer Error: Unable to locate required installation files
        ... 13 more

(Sep 29, 2021 20:04:34) Exiting with status -2

```

I just sent you an email, so hopefully we can work this more offline.

**Comment by jasonmeverett** [comment]
Okay, making progress @josmartin . Now, I've gotten updated files to work, and the MATLAB installer looks like it's working, HOWEVER, it looks as if Docker is getting stuck at:

```
Your installation may require additional configuration steps.

1. The following products require a supported compiler:

Stateflow
Simulink Coder
MATLAB Coder
Simulink Test
Embedded Coder

2. Simulink requires a C compiler for simulation acceleration, model reference, and MATLAB Function Block capabilities. It is recommended that you install a supported compiler on your machine.

3. To accelerate computations with the following products, a supported compiler is required:

Fixed-Point Designer

4. MATLAB Compiler SDK requires the following:

?  a supported compiler for creation of C and C++ Shared libraries
?  a Java JDK for creation of Java packages

(Sep 29, 2021 21:37:11) Exiting with status 0
(Sep 29, 2021 21:37:11) End - Successful

```

Docker does not seem to want to continue building after this message. Any ideas?

**Comment by jasonmeverett** [comment]
Yet another update. Just needed some patience :) 

@josmartin , I was able to get a successful install, but I'm still running into the same issue - the fact that I needed to pull in the license.dat file (since I'm on a networked license, the Dockerfile mentions this as a mandatory step). Please see my email and reach out to me at your earliest convenience so we can discuss more. Thanks!

**Comment by josmartin** [comment]
@jasonmeverett Have reached out - but to close out this chain 

1. The reason that it appeared that Docker didn't want to continue building after the install above is that it often takes "a long time" for Docker to commit the MATLAB install layer in the build - this is fairly dependent on the performance of the file system on which you are building the image.
2. To your final comment above - it is mandatory that there exist a license file (or license information) inside the container at the point you actually want to run MATLAB. Since you want to push this image to dockerhub and then pull and add license info later you can remove the `ENV MLM_LICENSE_FILE=` line in the `Dockerfile`, build with no license information at all. What you will need to tell your users is that at `docker run` time they will need (somehow) to provide license information to the container. You could ask them to add something like `-e MLM_LICENSE_FILE=27000@hostname` to the run command, or alternatively perhpas they have a network license file on disk and would cross-mount that inside the container using `-v path/to/lic:$MATLABROOT/licenses/network.lic` Hopefully you can see how each of these would bind in the license info at runtime?
