### ISSUE TITLE
Path issues in the final build stage.

### ISSUE THREAD

**Issue by bjacobs1** [mathworks-ref-arch/matlab-dockerfile#38]
In your Dockerfile there is a discrepancy which causes the symbolic link and the hint to where to put the license file to be incorrect. Either copy from /usr/local/MATLAB/Rxxxxx instead of from /usr/local/MATLAB when you copy your results to the final stage of the build process, or adjust the creation of the symbolic link and the hint to where to put the license file.

**Comment by hopedrivendeveloper** [comment]
@josmartin Despite line 49 `-destinationFolder /usr/local/MATLAB` while running `docker build -t matlab-r2021b --build-arg LICENSE_SERVER=27000@MyServerName .` Matlab indeed is installed into `/usr/local/MATLAB/R2021b`.
Had to modify line 56 to `COPY --from=middle-stage /usr/local/MATLAB/R2021b /usr/local/MATLAB` in order to make it working

**Comment by josmartin** [comment]
Expecting this to be fixed by an up-coming change to the `Dockerfile` next week. Thanks @hopedrivendeveloper and @bjacobs1 for highlighting this.

**Comment by prabhakk-mw** [comment]
These Dockerfiles have now been deprecated in Favor of installing MATLAB using MPM.
