### ISSUE TITLE
Installing Simulink as a Docker Matlab add-on

### ISSUE THREAD

**Issue by sfl0r3nz05** [mathworks-ref-arch/matlab-dockerfile#40]
I am able to install Simulink as a Docker Matlab add-on manually when the Matlab container is running. Is there a way to install Simulink more automatically, for example, using the `command` tag of `docker-compose`?

Thanks !!!

![simulink1](https://user-images.githubusercontent.com/6643905/143051996-981db5ad-fe3d-4f39-a38a-bc0b0b92ff85.png)
![simulink2](https://user-images.githubusercontent.com/6643905/143052001-852553df-910e-4ee8-8e31-1ca7a3bb96d4.png)

**Comment by josmartin** [comment]
@sfl0r3nz05 If you have already modified a container on a machine to which you have shell access you can use [these instructions](https://www.mathworks.com/help/cloudcenter/ug/save-changes-in-containers.html) to save your changed container as a new image. Then in the `docker-compose.yaml` file you would simply use the new image rather than `mathworks/matlab`.

**Comment by sfl0r3nz05** [comment]
Thank you, @josmartin. Following your recommendations, I took the snapshot of the Matlab image with Simulink added as an add-on. It works like a charm. The image created is in docker hub `sflorenz05/matlab_simulink:v0.1`.

I have documented the procedures followed in this [repo](https://github.com/sfl0r3nz05/ICSVirtual).
