### ISSUE TITLE
docker build error

### ISSUE THREAD

**Issue by donghaiwang** [mathworks-ref-arch/matlab-dockerfile#6]
sudo docker build . -t matlab:r2018a --build-arg MATLAB_RELEASE=R2018a --build-arg LICENSE_SERVER=/data/others/docker_matlab/matlab-dockerfile/license_standalone.lic

Step 8/22 : RUN cd /matlab-install     && ./install -mode silent -inputFile /matlab_installer_input.txt
 ---> Running in e98d7e04b390
/bin/sh: 1: ./install: Permission denied
The command '/bin/sh -c cd /matlab-install     && ./install -mode silent -inputFile /matlab_installer_input.txt' returned a non-zero code: 126

**Comment by josmartin** [comment]
This error means that you have not made the executable script named `install` in the matlab-install folder executable (which by default it is when you download from MathWorks). See https://www.gnu.org/software/bash/manual/html_node/Exit-Status.html for the meaning of exit code 126. I expect the fix for this is prior to undertaking the `docker build` command you should execute the following in the root folder of the git repo:

`chmod +x matlab-install/install`

**Comment by josmartin** [comment]
I've added this extra check step into the Dockerfile for 20a
