### ISSUE TITLE
Grayed icon after crash

### ISSUE THREAD

**Issue by DanRRRR** [mathworks-ref-arch/matlab-dockerfile#66]
We installed Matlab via MATLAB Package Manager, which was easy if you had just the initial experience with Linux. Another method  downloading it from Matlab and installing did not work. The only error or better say "missing feature" in your description was  that you forgot that damn necessary by unknown reason in Linux " ./ " before  mpm  ( looks like Linux Torwalds likes typing very much  :)  All was OK but then right after installation the outage happened and when computers restarted the Matlab icon was grayed and not functioning. Efforts putting it to life so far failed. The start of Matlab now requires to go inside the Matlab folder and running the same file from there. Or return back to Windows

Any idea how to fix that? Tried to reinstall Matlab with your mpm again but this does not have an option of fixing of installation (it refused to install already installed stuff )

**Comment by prabhakk-mw** [comment]
Hi @DanRRRR 

Thank you for your feedback regarding the missing `./` in our documentation for MPM. This information has been passed along for consideration to our documentation teams.

As for the issue related to the grayed out icon. MATLAB installed through the MATLAB Package Manager does not place icons on your desktop. This may have been placed by a previous install of MATLAB through the installer from the MathWorks website ?

It sounds like your installation of MATLAB through MPM was successful, as you are able to launch MATLAB from the folder in which it was installed using MPM.

The greyed out icons may suggest that the target application is unavailable. Maybe because the "Launcher Command" cannot run as the target does not exist.

Could you please try the following:

1. Place MATLAB on your system PATH using the following commands:
```bash
% assuming MATLAB is installed at /opt/matlab/R2023a
$ sudo ln -fs /opt/matlab/R2023a/bin/matlab /usr/local/bin/matlab

% verify MATLAB is on path by executing the WHICH command
$ which matlab
/usr/local/bin/matlab
```
2. Right clicking on the icon and select Properties
3. Update the "Launcher Command" to launch MATLAB with the appropriate flags as shown below:
```bash
matlab -desktop -licmode file
```
Or to use Online licensing
```bash
matlab -desktop -licmode online
```

Please let us know if this does not help resolve the issue.
Thank you!

**Comment by DanRRRR** [comment]
Thanks for respond. 
Respect Matlab icon on desktop i think i have to describe a bit differently. After installing (using your MPM, the other way to install did not go at all, even not started) and using Matlab during few hours before my PC power outage there was standard Matlab color icon on the desktop there. I was able to launch Matlab clicking on it. After outage this icon turned just into the text file (the icon of usual text file which looks like washed out image). Or may be there was another icon with the standard image, i do not remember. Exactly the same file exists in my home/userDir/matlab/bin/matlab. Clicking on this icon on desktop gives me nothing as it is grayed and has no picture. But doing ./matlab from bin directory launches Matlab ok. 
   I afraid to touch anything with Matlab because of heavily use it and need Matlab functioning, later i will try your method. I am still surprised that the product with millions of users does not behaves bullet-proof stable in Linux
