### ISSUE TITLE
Include the option to install xvfb to enable offline support package installation

### ISSUE THREAD

**Issue by gamlab-jlin** [mathworks-ref-arch/matlab-dockerfile#74]
In CI workflows the ability to install Support packages such as "CI/CD Automation for Simulink Check", it is recommended to use the Support package installer with "Silent Installation". By default the matlab-dockerfile does not install xvfb. (Currently mpm does not support installation of support packages.)

However, the example Dockerfile shipped with "CI/CD Automation for Simulink Check" does include it  when building from matlab-deps. But it mentions it as a dependency for mpm. (See attached)
[Dockerfile.txt](https://github.com/mathworks-ref-arch/matlab-dockerfile/files/12311167/Dockerfile.txt)

**Comment by prabhakk-mw** [comment]
Hi @gamlab-jlin 

Thank you for reaching out...

`MPM` does not depend on `xvfb`.

The comment in the attached Dockerfile, is listing it incorrectly. Probably because the owner wanted to re-use that layer to install `xvfb`, and forgot to update the comment above the layer.

Could you point me to the repository from which you downloaded this Dockerfile? I may be able to get in touch with the owners to update the comment accordingly.

Currently MPM only has the following dependencies, as listed in the [matlab-dockerfile Dockerfile](https://github.com/mathworks-ref-arch/matlab-dockerfile/blob/ab3002afe741d5b822bf9e9f072121496e4bc49a/Dockerfile#L37):
```
    wget 
    unzip 
    ca-certificates 
```

Given this information, is there any action that you would request w.r.t. the title of this issue?
`Include the option to install xvfb to enable offline support package installation`

I'm not sure I understand where you would like us to include XVFB, to simplify offline support package installation. Could you please explain if this is still relevant?

Thank you!

**Comment by gamlab-jlin** [comment]
Hi @prabhakk-mw,

Thank you for the quick reply.

The dockerfile is shipped with the support package "CI/CD Automation for Simulink Check", it is not part of any repository at least to my knowledge.

The documentation here (pdf page 98): mentions how to obtain it.
https://www.mathworks.com/content/dam/mathworks/mathworks-dot-com/hardware-support/files/ci-cd-automation-simulink-check-reference-book.pdf

![image](https://github.com/mathworks-ref-arch/matlab-dockerfile/assets/103584123/06353a67-fd1d-4aac-91cc-311a463f8da5)

I think it would be beneficial to mention that xvfb is needed for the offline support package installer (it searched for a display. Otherwise, it would fail to run if someone was trying to work with the matlab-dockerfile base.

Example log from a pipeline build that I have experienced.
```
#15 [build-without-polyspace 7/8] RUN tar -xzf cicd-offline-install.tar.gz &&     /opt/matlab/R2023a/bin/glnxa64/SupportSoftwareInstaller -downloadfolder ./SupportPackages/R2023a -inputFile ./SupportPackages/R2023a/ssi_input.txt
#15 0.690 terminate called after throwing an instance of '(anonymous namespace)::DisplayError'
#15 0.690   what():  No display available.
#15 0.815 Aborted (core dumped)
#15 ERROR: process "/bin/sh -c tar -xzf cicd-offline-install.tar.gz &&     /opt/matlab/R${MATLAB_VERSION}/bin/glnxa64/SupportSoftwareInstaller -downloadfolder ./SupportPackages/R${MATLAB_VERSION} -inputFile ./SupportPackages/R${MATLAB_VERSION}/ssi_input.txt" did not complete successfully: exit code: 134
------
 > [build-without-polyspace 7/8] RUN tar -xzf cicd-offline-install.tar.gz &&     /opt/matlab/R2023a/bin/glnxa64/SupportSoftwareInstaller -downloadfolder ./SupportPackages/R2023a -inputFile ./SupportPackages/R2023a/ssi_input.txt:
0.690 terminate called after throwing an instance of '(anonymous namespace)::DisplayError'
0.690   what():  No display available.
0.815 Aborted (core dumped)
------
```
I am sorry for the sparse information. I was writing it as I was trying to fix my pipelines. Please let me know if you need any further clarification.

Thank you,
Lin

**Comment by prabhakk-mw** [comment]
Hi @gamlab-jlin 

I've informed the `Simulink Check` teams about this issue, and have also updated the documentation for `mpm` in MPM.md with [this](https://github.com/mathworks-ref-arch/matlab-dockerfile/commit/b15d0a5546edfd1d2320db28fbf90f718eb9b387) commit.

Please contact [MathWorks Technical Support](https://in.mathworks.com/support/contact_us.html) for further updates related to this issue.
