### ISSUE TITLE
mpm install under macOS: Unable to extract the embedded archive

### ISSUE THREAD

**Issue by petermbauer** [mathworks-ref-arch/matlab-dockerfile#92]
Hi,
i am stuck with the MATLAB installation with `mpm` under macOS (mac Mini M1) using the downloaded offline installer files.
I started the "online installer" and selected "I want to download without installing" and the files were successfully downloaded into the `MathWorks/R2021b` folder.
When running `mpm` i get this error output. Not sure if `sudo` is required so i also tried it out:
```
./mpm install --source MathWorks/R2021b/2024_03_04_15_54_30 --products MATLAB
2024/03/04 16:49:23 Error: Unable to extract the embedded archive.
Unable to open file /var/folders/rg/hhfc3h9d30s215vqqxvq2z5w0000gn/T/mwse_3422692902/resources/MATLAB/en/stem3.xml.

sudo ./mpm install --source MathWorks/R2021b/2024_03_04_15_54_30 --products MATLAB
Password:
2024/03/04 16:51:17 Error: Unable to extract the embedded archive.
Unable to open file /tmp/mwse_4195026005/resources/MATLAB/en/stem3.xml.
```
The file at least seems to exist in the download folder though:
```
find MathWorks -name "stem3.xml"
MathWorks/R2021b/2024_03_04_15_54_30/resources/MATLAB/ko_KR/stem3.xml
MathWorks/R2021b/2024_03_04_15_54_30/resources/MATLAB/ja_JP/stem3.xml
MathWorks/R2021b/2024_03_04_15_54_30/resources/MATLAB/zh_CN/stem3.xml
MathWorks/R2021b/2024_03_04_15_54_30/resources/MATLAB/en/stem3.xml
```

Also tried both, the Intel and the ARM64 version of the mpm, same result. Same after re-downloading it.

The same procedure worked without any problems under Windows.

Any help or hints are greatly appreciated.

**Comment by drobinson0** [comment]
Hi,

This appears to be a known issue with  `mpm` , which will be fixed in an upcoming release. `mpm` is greedy in its use of file handles so if there is a too-low limit on the max file handles on your system, the software fails. You can verify this by (in the Docker container and on the host) running
```
ulimit -n
```
If this is any less than about 1200, then the bug will present itself. This can be worked around by increasing the file handle limit on the host machine or in the Docker container (depending on where the limit is set). It's likely to be a setting in the host, since Docker restricts controls of these limits by default in containers.

The file handle limit can be increased e.g., using the following command in the MacOS host:
```
sudo launchctl limit maxfiles 128000 524288
```
As mentioned, if running this command is not an option for you then a fix will be available in an upcoming release.

Let me know if this workaround helps, or if you still still see the issue.

Thanks!

David
